name: Build, Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t sonats/segundaimagempipe:v1.0 .

    - name: Push Docker Image
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username sonats --password-stdin
        docker push sonats/segundaimagempipe:v1.0

    - name: Deploy Application
      run: |
        # Comandos para implantar a aplicação usando a imagem Docker
